
package com.vivek.expensetrackerapp.core.util

object TestTags {
    const val HOME_SCREEN_TOP_APP_BAR_TAG = "HOME_SCREEN_TOP_APP_BAR_TAG"
    const val FLOATING_ACTION_BUTTON = "FLOATING_ACTION_BUTTON";
    const val CREATE_TRANSACTION_BUTTON = "CREATE_TRANSACTION_BUTTON"
    const val CREATE_TRANSACTION_CATEGORY_BUTTON ="CREATE_TRANSACTION_CATEGORY_BUTTON"

    const val CREATE_TRANSACTION_CATEGORY_INPUT = "CREATE_TRANSACTION_CATEGORY_INPUT"
    const val CREATE_TRANSACTION_CATEGORY_SAVE_BUTTON = "CREATE_TRANSACTION_CATEGORY_SAVE_BUTTON"

    const val TRANSACTIONS_CATEGORIES_DROPDOWN = "TRANSACTIONS_CATEGORIES_DROPDOWN"

    const val GENERAL_DROPDOWN = "GENERAL_DROPDOWN"

}